Sprint 12 Pull Request
etdevios/ImageFeed pull request #5
Opened 2023-03-23 20:45 UTC by etdevios

2023-03-24 18:12 UTC, protos17 requested changes

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/ImagesList/ImagesListViewController.swift
>          let formattedDate = dateFormatter.string(from: Date())
Здесь мы должны присваивать значение из createdAt

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +    private func clean() {
Стоит метод называть более информативно, например, cleanCache

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/AppDelegates/SceneDelegate.swift
>          // Use this method to save data, release shared resources, and store enough scene-specific state information
Сгенерированный закомментированный код можно удалить

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +                print(error)
Рекомендую заменить print на assertionFailure, для отлова ошибок

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +        guard let url = urlComponents?.url else { fatalError("Failed to create URL") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +        guard let token = OAuth2TokenStorage().token else { fatalError("Failed to create token") }
Рекомендую тоже заменить на assertionFailure

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +        guard let url = urlComponents?.url else { fatalError("Failed to create URL") }
Рекомендую заменить на assertionFailure

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +        guard let token = OAuth2TokenStorage().token else { fatalError("Failed to create token") }
Рекомендую также заменить на assertionFailure

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/ImagesList/ImagesListCell.swift
> +    @objc func likeButtonClicked() {
Рекомендую указать как private

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +            guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration") }
Рекомендую использовать assertionFailure

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +            fatalError("Could not get cgImage!")
Рекомендую использовать assertionFailure

2023-03-24 18:12 UTC, protos17 commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +            fatalError("Could not load SF Symbol: \(sfSymbolName)!")
Рекомендую использовать assertionFailure

2023-03-25 20:52 UTC, etdevios commented
Добрый вечер, исправил замечания и предложения. Подскажите пожалуйста, что еще можно добавить, изменить или внедрить. Заранее спасибо!

2023-03-25 21:02 UTC, protos17 commented
Можешь попробовать еще избавиться от эффекта, когда после успешной авторизации и закрытии вебвью на некоторое время появляется AuthViewController

2023-03-26 12:04 UTC, etdevios commented
Исправлено) Есть еще, на что надо обратить внимание и доработать? Может иерархия самих фалов или какие-то другие предложения?)

2023-03-26 21:33 UTC, protos17 approved these changes

2023-03-26 21:33 UTC, protos17 commented on ImageFeed/Services/ImageListService/ImagesListService.swift
> +        guard let token = OAuth2TokenStorage().token else {
Рекомендую OAuth2TokenStorage сделать как синглтон и обращаться через shared

2023-03-26 21:33 UTC, protos17 commented on ImageFeed/ViewControllers/Auth/AuthViewController.swift
> +        view.backgroundColor = .black
Здесь должен быть цвет YP Black

2023-03-26 21:33 UTC, protos17 commented on ImageFeed/ViewControllers/ImagesList/ImagesListViewController.swift
> +        let formattedDate = dateFormatter.string(from: photo.createdAt ?? Date())
Рекомендую лейбл оставлять пустым при отсутствии значения

2023-03-26 21:33 UTC, protos17 commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +        avatarImageView.kf.setImage(with: url, placeholder: placeholder) {_ in
Нужно добавить weak self, чтобы не было сильной ссылки

2023-03-27 14:02 UTC, protos17 commented
> Исправлено) Есть еще, на что надо обратить внимание и доработать? Может иерархия самих фалов или какие-то другие предложения?)
> 
> 

Больше у меня нет предложений)

2023-03-28 19:26 UTC, merged